<a href="https://colab.research.google.com/github/lydialuggu2005-yes/Intro-to-data-analysis/blob/main/Day_2_Boot_camp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [39]:
import pandas as pd

cafe_order = pd.read_csv('day2_cafe_orders.csv')
#cafe_order.shape

#cafe_order. info()

cafe_order.describe()
cafe_order.head(10)
#print(f"this data the following rows and columns {cafe_order.shape}")
#print(f"the data  info is {cafe_order. info()}")


#cafe_order.isna().sum()
#cafe_order.isna().any(axis=1)
cafe_order[cafe_order["unit_price"].isna()]

cafe_order.dropna(subset=["unit_price"])

,order_id,timestamp,branch,customer_name,drink,size,quantity,unit_price,payment,barista
0,ORD-00001,2025-08-19 15:24:00,Birmingham Central,NaN,Latte,L,2,4.2,Card,Sarah
1,ORD-00002,2025-08-08 08:33:00,birmingham central,NaN,ICED LATTE,M,1,Free,Card,Liam
2,ORD-00003,2025-08-01T18:53:00,Solihul,NaN,Hot Chocolate,Med,1,4.0,cAsh,CHEN
3,ORD-00004,24/09/2025 08:08,Wolverhampton,Hassan Smith,Latte,M,2,3.8,Cash,Marco
4,ORD-00005,2025-09-09 13:54:00,Solihull,Finn Evans,Iced Latte,M,1,4.3,Mobile,Hannah
...,...,...,...,...,...,...,...,...,...,...
5220,ORD-03185,17/08/2025 09:15,Wolverhampton,NaN,Latte,M,1,3.8,cash,Lena
5221,ORD-01762,2025-07-16 10:29:00,Wolverhampton,Emma Khan,Latte,small,1,£3.40,Card,Priya
5222,ORD-04395,2025-08-11 05:33:00,Solihul,Carla Evans,Mocha,Med,1,4.2,cash,Chen
5223,ORD-00315,2025-09-09T16:34:00,wolves,Pavel Walker,Hot Chocolate,M,1,4.00,cAsh,Hannah
5224,ORD-02130,2025-09-26 03:30:00,birmingham central,Kira Hall,Mocha,S,1,3.8,Card,Sarah

In [1]:
from google.colab import files
uploaded = files.upload()

Saving employee_survey.csv to employee_survey.csv

In [23]:
 import pandas as pd
 employee = pd.read_csv("employee_survey.csv")
 employee.head()

,respondent_id,department,satisfaction,wfh_days,free_comment,recommend_friend
0,R001,HR,2.0,2.0,Great team,5.0
1,R002,HR,1.0,5.0,Workload heavy,5.0
2,R003,Sales,1.0,5.0,Workload heavy,1.0
3,R004,Sales,4.0,4.0,NaN,1.0
4,R005,Marketing,2.0,4.0,NaN,1.0

In [24]:
employee.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   respondent_id     120 non-null    object
 1   department        120 non-null    object
 2   satisfaction      114 non-null    float64
 3   wfh_days          120 non-null    float64
 4   free_comment      102 non-null    object
 5   recommend_friend  116 non-null    float64
dtypes: float64(3), object(3)
memory usage: 5.8+ KB

In [25]:
employee.isna().sum()

respondent_id        0
department           0
satisfaction         6
wfh_days             0
free_comment        18
recommend_friend     4
dtype: int64

In [29]:
employee[employee["free_comment"].isna()]

,respondent_id,department,satisfaction,wfh_days,free_comment,recommend_friend
3,R004,Sales,4.0,4.0,NaN,1.0
4,R005,Marketing,2.0,4.0,NaN,1.0
10,R011,Marketing,2.0,4.0,NaN,1.0
14,R015,Marketing,3.0,5.0,NaN,4.0
45,R046,Sales,4.0,4.0,NaN,5.0
47,R048,HR,5.0,2.0,NaN,5.0
49,R050,Finance,1.0,2.0,NaN,2.0
53,R054,Sales,2.0,1.0,NaN,2.0
56,R057,HR,5.0,1.0,NaN,3.0
63,R064,Marketing,1.0,4.0,NaN,2.0
78,R079,Marketing,2.0,3.0,NaN,2.0
85,R086,Marketing,2.0,2.0,NaN,2.0
93,R094,Sales,NaN,0.0,NaN,2.0
99,R100,Engineering,1.0,1.0,NaN,5.0
101,R102,Sales,NaN,0.0,NaN,2.0
102,R103,Finance,2.0,4.0,NaN,3.0
111,R112,Sales,5.0,4.0,NaN,4.0
113,R114,Sales,4.0,1.0,NaN,5.0

In [6]:
import pandas as pd
care_home = pd.read_csv("day2_care_home_records.csv")

care_home.duplicated().sum()
care_home = care_home.drop_duplicates().head(10)
#care_home[care_home.duplicated(keep=False)].sort_values(by=list(care_home.columns)).head(10)


care_home.drop_duplicates(
    subset="resident_id",
    keep="first"
)
#care_home[care_home.duplicated()]

,record_id,timestamp,resident_id,resident_name,age,sex,medication,dose_mg,administered_by,diet
0,REC-00001,2025-05-01 19:41,R1003,Bernard Chapman,83,M,Bisoprolol,2.5mg,HCA Adeyemi,SOFT
1,REC-00002,25/01/2025 23:48,R1042,Margaret Chapman,80,M,Donepezil,5.0,RN Thompson,Standard
2,REC-00003,2025-04-07 19:27,R1037,Stanley Walker,77,F,Donepezil,5.0,HCA Brown,Soft
3,REC-00004,16/04/2025 22:22,R1018,Doris Howell,94,F,Ramipril,NaN,RN Williams,Vegetarian
4,REC-00005,03 Mar 2025 09:41,R1073,Phyllis Chapman,76,F,Amlodipine,5.0mg,HCA Brown,Pureed
5,REC-00006,2025-02-13 13:35,R1002,Albert Foster,94,M,Bisoprolol,2.5,HCA Garcia,Standard
6,REC-00007,06 Jan 2025 21:46,R1030,Beryl Carter,90,F,Aspirin,75.0,RN Williams,Diabetic
7,REC-00008,2025-04-11 14:26,R1012,Joyce Murphy,84,F,Ramipril,5.0,RN Williams,soft diet
8,REC-00009,2025-04-10 01:09,R1014,Margaret Mitchell,86,F,Ramipril,5.0,RN Thompson,Pureed
9,REC-00010,31/01/2025 01:40,R1070,Albert Chapman,68,M,Metformin,500.0,HCA Brown,Soft

In [16]:
import pandas as pd
care_home = pd.read_csv("day2_care_home_records.csv")

#care_home.duplicated().sum()
#clean = care_home.drop_duplicates()
care_home[care_home.duplicated(keep=False)].sort_values(by=list(care_home.columns)).head(10)

clean[clean.duplicated(keep=False)].sort_values(by=list(clean.columns)).head(10)

#care_home.drop_duplicates(
#   subset="resident_id",
#   keep="first"
#)
#care_home[care_home.duplicated()]

Empty DataFrame
Columns: [record_id, timestamp, resident_id, resident_name, age, sex, medication, dose_mg, administered_by, diet]
Index: []

In [27]:
import pandas as pd
cafe_order = pd.read_csv('day2_cafe_orders.csv')


cafe_order["barista"].value_counts()

barista
Liam       381
Sarah      377
Marco      367
Olu        366
Yusuf      365
Priya      363
Hannah     345
Chen       341
Lena       337
Aisha      334
 Aisha      54
marco       49
Priya       48
Marco       48
HANNAH      47
Liam        47
aisha       46
 Marco      45
olu         45
liam        44
Sarah       44
yusuf       44
Chen        43
Lena        43
chen        43
 Liam       43
CHEN        43
 Lena       43
Yusuf       43
YUSUF       41
OLU         41
 Sarah      40
PRIYA       40
priya       39
Olu         39
 Olu        38
LIAM        37
Hannah      37
 Priya      36
lena        36
AISHA       36
hannah      35
MARCO       35
 Chen       34
 Yusuf      33
SARAH       33
 Hannah     32
LENA        31
sarah       28
Aisha       26
Name: count, dtype: int64

In [33]:
import pandas as pd
cafe_order = pd.read_csv('day2_cafe_orders.csv')


cafe_order["barista"].value_counts()
cafe_order["barista"].str.strip().str.title().value_counts()

barista
Liam      552
Marco     544
Olu       529
Priya     526
Yusuf     526
Sarah     522
Chen      504
Hannah    496
Aisha     496
Lena      490
Name: count, dtype: int64

In [34]:
import pandas as pd
cafe_order = pd.read_csv('day2_cafe_orders.csv')


cafe_order["barista"].value_counts()
cafe_order["barista"].str.strip().str.title().value_counts()

cafe_order.head(20)

,order_id,timestamp,branch,customer_name,drink,size,quantity,unit_price,payment,barista
0,ORD-00001,2025-08-19 15:24:00,Birmingham Central,NaN,Latte,L,2,4.2,Card,Sarah
1,ORD-00002,2025-08-08 08:33:00,birmingham central,NaN,ICED LATTE,M,1,Free,Card,Liam
2,ORD-00003,2025-08-01T18:53:00,Solihul,NaN,Hot Chocolate,Med,1,4.0,cAsh,CHEN
3,ORD-00004,24/09/2025 08:08,Wolverhampton,Hassan Smith,Latte,M,2,3.8,Cash,Marco
4,ORD-00005,2025-09-09 13:54:00,Solihull,Finn Evans,Iced Latte,M,1,4.3,Mobile,Hannah
5,ORD-00006,2025-09-09 22:29:00,Wolverhampton,Ravi Evans,Tea,S,2,2.5,cash,Yusuf
6,ORD-00007,26/07/2025 10:43,Solihull,Alice Smith,Flat White,S,1,3.3,GPay,Chen
7,ORD-00008,17/09/2025 04:02,solihull,NaN,Mocha,M,200,4.2,Card,Chen
8,ORD-00009,2025-07-31 11:50:00,Birmingham Central,Jacob Hughes,Cappuccino,L,1,4.3,Cash,Chen
9,ORD-00010,09/08/2025 21:25,b'ham central,Ravi Walker,Iced Latte,M,1,4.3,Mobile,Sarah
10,ORD-00011,2025-07-19 15:50:00,Birmingham Central,Quinn Davies,Flat White,M,1,3.70,Cash,Marco
11,ORD-00012,2025-08-09 22:29:00,Wolverhampton,Jacob Jones,Flat White,L,1,4.1,Cash,Liam
12,ORD-00013,2025-09-12 07:30:00,Solihull,NaN,Tea,L,1,3.3,Card,Sarah
13,ORD-00014,2025-07-07 15:57:00,Solihull,Kira Evans,Latte,M,1,3.8,Card,chen
14,ORD-00015,2025-07-31 14:16:00,Solihull,Hassan Evans,latte,Lg,3,4.2,Card,Hannah
15,ORD-00016,18/07/2025 13:05,Birmingham Central,NaN,Americano,S,3,2.8,Card,Chen
16,ORD-00017,2025-07-22 13:55:00,Wolverhampton,Olivia Taylor,Flat White,S,3,3.3,Card,Yusuf
17,ORD-00018,2025-09-16T15:56:00,Solihull,Mia Khan,Cappuccino,Medium,1,3.9,Mobile,LENA
18,ORD-00019,2025-07-12 19:15:00,Solihull,Leo Khan,Latte,M,1,3.8,Apple Pay,OLU
19,ORD-00020,04/07/2025 13:48,Solihul,Alice Hughes,Cappuccino,M,1,3.9,Card,Lena

In [41]:
import pandas as pd
cafe_order = pd.read_csv('day2_cafe_orders.csv')


cafe_order["barista"].value_counts()
cafe_order["barista"].str.strip().str.title().value_counts()

cafe_order.head(20)

#cafe_order["unit_price"] = pd.to_numeric(
#   cafe_order["unit_price"].str.replace("£", ""),
#   errors="coerce"
#)

,order_id,timestamp,branch,customer_name,drink,size,quantity,unit_price,payment,barista
0,ORD-00001,2025-08-19 15:24:00,Birmingham Central,NaN,Latte,L,2,4.2,Card,Sarah
1,ORD-00002,2025-08-08 08:33:00,birmingham central,NaN,ICED LATTE,M,1,Free,Card,Liam
2,ORD-00003,2025-08-01T18:53:00,Solihul,NaN,Hot Chocolate,Med,1,4.0,cAsh,CHEN
3,ORD-00004,24/09/2025 08:08,Wolverhampton,Hassan Smith,Latte,M,2,3.8,Cash,Marco
4,ORD-00005,2025-09-09 13:54:00,Solihull,Finn Evans,Iced Latte,M,1,4.3,Mobile,Hannah
5,ORD-00006,2025-09-09 22:29:00,Wolverhampton,Ravi Evans,Tea,S,2,2.5,cash,Yusuf
6,ORD-00007,26/07/2025 10:43,Solihull,Alice Smith,Flat White,S,1,3.3,GPay,Chen
7,ORD-00008,17/09/2025 04:02,solihull,NaN,Mocha,M,200,4.2,Card,Chen
8,ORD-00009,2025-07-31 11:50:00,Birmingham Central,Jacob Hughes,Cappuccino,L,1,4.3,Cash,Chen
9,ORD-00010,09/08/2025 21:25,b'ham central,Ravi Walker,Iced Latte,M,1,4.3,Mobile,Sarah
10,ORD-00011,2025-07-19 15:50:00,Birmingham Central,Quinn Davies,Flat White,M,1,3.70,Cash,Marco
11,ORD-00012,2025-08-09 22:29:00,Wolverhampton,Jacob Jones,Flat White,L,1,4.1,Cash,Liam
12,ORD-00013,2025-09-12 07:30:00,Solihull,NaN,Tea,L,1,3.3,Card,Sarah
13,ORD-00014,2025-07-07 15:57:00,Solihull,Kira Evans,Latte,M,1,3.8,Card,chen
14,ORD-00015,2025-07-31 14:16:00,Solihull,Hassan Evans,latte,Lg,3,4.2,Card,Hannah
15,ORD-00016,18/07/2025 13:05,Birmingham Central,NaN,Americano,S,3,2.8,Card,Chen
16,ORD-00017,2025-07-22 13:55:00,Wolverhampton,Olivia Taylor,Flat White,S,3,3.3,Card,Yusuf
17,ORD-00018,2025-09-16T15:56:00,Solihull,Mia Khan,Cappuccino,Medium,1,3.9,Mobile,LENA
18,ORD-00019,2025-07-12 19:15:00,Solihull,Leo Khan,Latte,M,1,3.8,Apple Pay,OLU
19,ORD-00020,04/07/2025 13:48,Solihul,Alice Hughes,Cappuccino,M,1,3.9,Card,Lena

In [53]:
cafe_order.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5225 entries, 0 to 5224
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       5225 non-null   object
 1   timestamp      5225 non-null   object
 2   branch         5225 non-null   object
 3   customer_name  3670 non-null   object
 4   drink          5225 non-null   object
 5   size           5225 non-null   object
 6   quantity       5225 non-null   object
 7   unit_price     5205 non-null   object
 8   payment        5225 non-null   object
 9   barista        5185 non-null   object
dtypes: object(10)
memory usage: 408.3+ KB

In [56]:
cafe_order['quantity'] = pd.to_numeric(
    cafe_order['quantity'],
    errors = 'coerce'

)

In [68]:
# IQR method — robust, no assumptions about distribution
q1, q3 = cafe_order["quantity"].quantile([0.25, 0.75])
iqr    = q3 - q1
lo, hi = q1 - 1.5*iqr,  q3 + 1.5*iqr

flagged =  cafe_order[(cafe_order["quantity"] < lo) |
             (cafe_order["quantity"] > hi)]
cafe_order["quantity"] = cafe_order["quantity"].clip(lo, hi)

In [67]:
print(flagged)

    order_id         timestamp    branch customer_name  drink size  quantity  \
7  ORD-00008  17/09/2025 04:02  solihull           NaN  Mocha    M     200.0

  unit_price payment barista
7        4.2   Card     Chen

In [66]:
print(lo,hi)

-0.5 3.5